import requests
import json
import numpy as np
import pandas as pd
import random
import math
import sys
sys.path.append(r'../config')
sys.path.append('config')
from sdc_4 import config
import matplotlib.pyplot as plt

def test_fnc(sequence,thread=0):
    server = 'orchestrator'
    action = 'addExperiment'
    params = dict(experiment=json.dumps(sequence),thread=thread)
    print("requesting")
    requests.post("http://{}:{}/{}/{}".format(
        config['servers']['orchestrator']['host'], 13380, server, action), params=params).json()

### Real wafer coordinates
df = pd.read_csv(r'C:\Users\LaborRatte23-2\Documents\SDC functions\Python scripts\df_109.csv').to_numpy()
random.seed(843)
XY, C, I, Q, m = df[:,0:2], df[:,2:5], 2*df[:,-3], df[:,-2], df[:,-1]
X, Y = XY[:,0], XY[:,1]
x_query = np.array([[i, j] for i, j in zip(X, Y)])
query = json.dumps({'x_query': x_query.tolist(), 'c_query': C.tolist(), 'i_query': I.tolist(), 'q_query': Q.tolist(), 'm_query': m.tolist()})
id0 = random.randint(0, len(X))
x0, y0, I0 = X[id0], Y[id0], I[id0]

substrate = 109
z = 13.5

### 1st iteration start from random point without orchestrator modify

test_fnc(dict(soe=['orchestrator/start', f'lang/moveWaste_{0}', f'hamilton/pumpL_{0}', f'hamilton/pumpR_{0}', f'lang/moveWaste_{1}', 
                    f'lang/moveWaste_{2}', f'lang/moveWaste_{3}', f'lang/moveWaste_{4}', f'hamilton/pumpL_{1}', f'lang/moveSample_{0}',
                    f'lang/moveDown_{0}', f'lang/getPos_{0}', f'hamilton/pumpL_{2}', f'hamilton/pumpL_{3}', f'hamilton/pumpL_{4}', 
                    f'hamilton/pumpL_{5}', f'hamilton/pumpL_{6}', f'autolab/measure_{0}', f'autolab/measure_{1}', f'autolab/measure_{2}',
                    f'autolab/measure_{3}', f'autolab/measure_{4}', f'autolab/measure_{5}', f'hamilton/pumpL_{7}', f'lang/moveRel_{0}',
                    f'hamilton/pumpL_{8}', f'lang/moveRel_{1}', f'hamilton/pumpL_{9}', f'lang/moveWaste_{5}', f'analysis/eis0_{0}', f'analysis/eis1_{0}'], 
            params={'start': {'collectionkey' : f'substrate_{substrate}'},
                    f'moveWaste_{0}':{'x': 0, 'y':0, 'z': 0},
                    f'pumpL_{0}': {'volume': 125, 'times': 3},
                    f'pumpR_{0}': {'volume': 0, 'times': 1},
                    f'moveWaste_{1}':{'x': 25.3, 'y': -14.7, 'z': 9.2},
                    f'moveWaste_{2}':{'x': 25.3, 'y': -14.7, 'z': 0},
                    f'moveWaste_{3}':{'x': 25.3, 'y': -14.7, 'z': 9.2},
                    f'moveWaste_{4}':{'x': 25.3, 'y': -14.7, 'z': 0},
                    f'pumpL_{1}': {'volume': 0, 'times': 1},
                    f'moveSample_{0}': {'x': x0, 'y': y0, 'z': z}, 
                    f'moveDown_{0}': {'dz': 0.005, 'steps': 400, 'maxForce': 7900.0, 'threshold': 0.12},
                    f'getPos_{0}': {},
                    f'pumpL_{2}': {'volume': 10, 'times': 1},
                    f'pumpL_{3}': {'volume': -10, 'times': 1},
                    f'pumpL_{4}': {'volume': 10, 'times': 1},
                    f'pumpL_{5}': {'volume': -10, 'times': 1},
                    f'pumpL_{6}': {'volume': 30, 'times': 1},
                    f'measure_{0}':{'procedure': 'ocp_rs', 
                                    'setpointjson': json.dumps({'recordsignal': {'Duration': 30, 'Interval time in µs': 1}}),
                                    'plot': "tCV",
                                    'onoffafter': "off",
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, 4, 0),
                                    'parseinstructions':'recordsignal'},
                    f'measure_{1}':{'procedure': 'eis_fast',
                                    'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                    'plot': 'impedance',
                                    'onoffafter': 'off',
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, 4, 0),
                                    'parseinstructions': ['FIAMeasPotentiostatic'],
                                    'substrate': substrate,
                                    'id': 0,
                                    'experiment': 0},
                    f'measure_{2}': {'procedure': 'charge',
                                    'setpointjson': json.dumps({'switchgalvanostatic': {'WE(1).Current range': 1+round(math.log10(I0))},
                                                                'applycurrent': {'Setpoint value': -I0},
                                                                'recordsignal': {'Duration': 9000,
                                                                                 'Interval time in µs': 1}}),
                                    'plot': 'tCV',
                                    'onoffafter': 'off',
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_cp_charge_{:03d}_{}.nox'.format(substrate, 4, 1),
                                    'parseinstructions': 'recordsignal'},
                    f'measure_{3}': {'procedure': 'discharge',
                                    'setpointjson': json.dumps({'switchgalvanostatic': {'WE(1).Current range': 1+round(math.log10(I0))},
                                                                'applycurrent': {'Setpoint value': I0},
                                                                'recordsignal': {'Duration': 9000,
                                                                                 'Interval time in µs': 1}}),
                                    'plot': 'tCV',
                                    'onoffafter': 'off',
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_cp_discharge_{:03d}_{}.nox'.format(substrate, 4, 1),
                                    'parseinstructions': 'recordsignal'},
                    f'measure_{4}':{'procedure': 'ocp_rs', 
                                    'setpointjson': json.dumps({'recordsignal': {'Duration': 90, 'Interval time in µs': 1}}),
                                    'plot': "tCV",
                                    'onoffafter': "off",
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, 4, 1),
                                    'parseinstructions':'recordsignal'},
                    f'measure_{5}':{'procedure': 'eis_fast',
                                    'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                    'plot': 'impedance',
                                    'onoffafter': 'off',
                                    'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                    'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, 4, 1),
                                    'parseinstructions': ['FIAMeasPotentiostatic'],
                                    'substrate': substrate,
                                    'id': 0,
                                    'experiment': 1},
                    f'pumpL_{7}': {'volume': -75, 'times': 1},
                    f'moveRel_{0}':{'dx': 0, 'dy':0, 'dz':-0.5},
                    f'pumpL_{8}': {'volume': -50, 'times': 1},
                    f'moveRel_{1}':{'dx': 0, 'dy':0, 'dz':-0.5},
                    f'pumpL_{9}': {'volume': -50, 'times': 1},
                    f'moveWaste_{5}':{'x': 0, 'y':0, 'z': 0},
                    f'eis0_{0}': {'run': 0, 'address':json.dumps([f"experiment_{0}:0/measure_{1}/data/data/FIAMeasPotentiostatic/Z'",
                                                            f"experiment_{0}:0/measure_{1}/data/data/FIAMeasPotentiostatic/-Z''",
                                                            f"experiment_{0}:0/measure_{1}/data/data/FIAMeasPotentiostatic/Frequency"])},  
                    f'eis1_{0}': {'run': 1, 'address':json.dumps([f"experiment_{0}:0/measure_{5}/data/data/FIAMeasPotentiostatic/Z'",
                                                        f"experiment_{0}:0/measure_{5}/data/data/FIAMeasPotentiostatic/-Z''",
                                                        f"experiment_{0}:0/measure_{5}/data/data/FIAMeasPotentiostatic/Frequency"])}},
            meta=dict()))

### 29 more iterations with orchestrator modify

for i in range(29):
    test_fnc(dict(soe=[f'orchestrator/modify_{i}', f'lang/moveWaste_{6*(i+1)}', f'hamilton/pumpL_{10*(i+1)}', f'hamilton/pumpR_{i+1}', f'lang/moveWaste_{6*(i+1)+1}', 
                    f'lang/moveWaste_{6*(i+1)+2}', f'lang/moveWaste_{6*(i+1)+3}', f'lang/moveWaste_{6*(i+1)+4}', f'hamilton/pumpL_{10*(i+1)+1}', f'lang/moveSample_{i+1}',
                    f'lang/moveDown_{i+1}', f'lang/getPos_{i+1}', f'hamilton/pumpL_{10*(i+1)+2}', f'hamilton/pumpL_{10*(i+1)+3}', f'hamilton/pumpL_{10*(i+1)+4}', 
                    f'hamilton/pumpL_{10*(i+1)+5}', f'hamilton/pumpL_{10*(i+1)+6}', f'autolab/measure_{14*(i+1)}', f'autolab/measure_{14*(i+1)+1}', f'autolab/measure_{14*(i+1)+2}',
                    f'autolab/measure_{14*(i+1)+3}', f'autolab/measure_{14*(i+1)+4}', f'autolab/measure_{14*(i+1)+5}', f'autolab/measure_{14*(i+1)+6}', f'autolab/measure_{14*(i+1)+7}',
                    f'autolab/measure_{14*(i+1)+8}', f'autolab/measure_{14*(i+1)+9}', f'autolab/measure_{14*(i+1)+10}', f'autolab/measure_{14*(i+1)+11}', f'autolab/measure_{14*(i+1)+12}',
                    f'autolab/measure_{14*(i+1)+13}', f'hamilton/pumpL_{10*(i+1)+7}', f'lang/moveRel_{2*(i+1)}', f'hamilton/pumpL_{10*(i+1)+8}', f'lang/moveRel_{2*(i+1)+1}',
                    f'hamilton/pumpL_{10*(i+1)+9}', f'lang/moveWaste_{6*(i+1)+5}', f'analysis/cp_{i+1}', f'analysis/ocp_{i+1}', f'analysis/eis0_{(i+1)}',
                    f'analysis/eis1_{3*(i+1)}', f'analysis/eis1_{3*(i+1)+1}', f'analysis/eis1_{3*(i+1)+2}', f'ml/activeLearningGaussian_{i+1}'],
            params={f'modify_{i}': {'addresses':[f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_x',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_y',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_ci',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_di',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_ci',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_di',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_ci',
                                                 f'experiment_{i}:0/activeLearningGaussian_{i}/data/next_di'],
                                    'pointers':[f'moveSample_{i+1}/x', f'moveSample_{i+1}/y', f'measure_{14*(i+1)+2}/setpointjson', f'measure_{14*(i+1)+3}/setpointjson',
                                                f'measure_{14*(i+1)+6}/setpointjson', f'measure_{14*(i+1)+7}/setpointjson', f'measure_{14*(i+1)+10}/setpointjson', f'measure_{14*(i+1)+11}/setpointjson']}, # correct ml_action for measure_cp
                    f'moveWaste_{6*(i+1)}':{'x': 0, 'y':0, 'z': 0},
                    f'pumpL_{10*(i+1)}': {'volume': 125, 'times': 3},
                    f'pumpR_{(i+1)}': {'volume': 0, 'times': 1},
                    f'moveWaste_{6*(i+1)+1}':{'x': 25.3, 'y': -14.7, 'z': 9.2},
                    f'moveWaste_{6*(i+1)+2}':{'x': 25.3, 'y': -14.7, 'z': 0},
                    f'moveWaste_{6*(i+1)+3}':{'x': 25.3, 'y': -14.7, 'z': 9.2},
                    f'moveWaste_{6*(i+1)+4}':{'x': 25.3, 'y': -14.7, 'z': 0},
                    f'pumpL_{10*(i+1)+1}': {'volume': 0, 'times': 1},
                    f'moveSample_{i+1}': {'x': '?', 'y': '?', 'z': z}, 
                    f'moveDown_{i+1}': {'dz': 0.005, 'steps': 400, 'maxForce': 7900.0, 'threshold': 0.12},
                    f'getPos_{i+1}': {},
                    f'pumpL_{10*(i+1)+2}': {'volume': 10, 'times': 1},
                    f'pumpL_{10*(i+1)+3}': {'volume': -10, 'times': 1},
                    f'pumpL_{10*(i+1)+4}': {'volume': 10, 'times': 1},
                    f'pumpL_{10*(i+1)+5}': {'volume': -10, 'times': 1},
                    f'pumpL_{10*(i+1)+6}': {'volume': 30, 'times': 1},
                    f'measure_{14*(i+1)}': {'procedure': 'ocp_rs', 
                                        'setpointjson': json.dumps({'recordsignal': {'Duration': 60, 'Interval time in µs': 1}}),
                                        'plot': "tCV",
                                        'onoffafter': "off",
                                        'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                        'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, int(i+1), 0),
                                        'parseinstructions':'recordsignal'},
                    f'measure_{14*(i+1)+1}': {'procedure': 'eis_fast',
                                        'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                        'plot': 'impedance',
                                        'onoffafter': 'off',
                                        'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                        'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, int(i+1), 0),
                                        'parseinstructions': ['FIAMeasPotentiostatic'],
                                        'substrate': substrate,
                                        'id': int(i+1),
                                        'experiment': 0},
                    f'measure_{14*(i+1)+2}': {'procedure': 'charge',
                                           'setpointjson': '?',
                                           'plot': 'tCV',
                                           'onoffafter': 'off',
                                           'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                           'filename': 'substrate_{}_cp_charge_{:03d}_{}.nox'.format(substrate, int(i+1), 1),
                                           'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+3}': {'procedure': 'discharge',
                                            'setpointjson': '?',
                                            'plot': 'tCV',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_cp_discharge_{:03d}_{}.nox'.format(substrate, int(i+1), 1),
                                            'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+4}': {'procedure': 'ocp_rs', 
                                            'setpointjson': json.dumps({'recordsignal': {'Duration': 180, 'Interval time in µs': 1}}),
                                            'plot': "tCV",
                                            'onoffafter': "off",
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, int(i+1), 1),
                                            'parseinstructions':'recordsignal'},
                    f'measure_{14*(i+1)+5}': {'procedure': 'eis',
                                            'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                            'plot': 'impedance',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, int(i+1), 1),
                                            'parseinstructions': ['FIAMeasPotentiostatic'],
                                            'substrate': substrate,
                                            'id': int(i+1),
                                            'experiment': 1},
                    f'measure_{14*(i+1)+6}': {'procedure': 'charge',
                                           'setpointjson': '?',
                                           'plot': 'tCV',
                                           'onoffafter': 'off',
                                           'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                           'filename': 'substrate_{}_cp_charge_{:03d}_{}.nox'.format(substrate, int(i+1), 2),
                                           'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+7}': {'procedure': 'discharge',
                                            'setpointjson': '?',
                                            'plot': 'tCV',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_cp_discharge_{:03d}_{}.nox'.format(substrate, int(i+1), 2),
                                            'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+8}': {'procedure': 'ocp_rs', 
                                            'setpointjson': json.dumps({'recordsignal': {'Duration': 180, 'Interval time in µs': 1}}),
                                            'plot': "tCV",
                                            'onoffafter': "off",
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, int(i+1), 2),
                                            'parseinstructions':'recordsignal'},
                    f'measure_{14*(i+1)+9}': {'procedure': 'eis',
                                            'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                            'plot': 'impedance',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, int(i+1), 2),
                                            'parseinstructions': ['FIAMeasPotentiostatic'],
                                            'substrate': substrate,
                                            'id': int(i+1),
                                            'experiment': 2},
                    f'measure_{14*(i+1)+10}': {'procedure': 'charge',
                                           'setpointjson': '?',
                                           'plot': 'tCV',
                                           'onoffafter': 'off',
                                           'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                           'filename': 'substrate_{}_cp_charge_{:03d}_{}.nox'.format(substrate, int(i+1), 3),
                                           'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+11}': {'procedure': 'discharge',
                                            'setpointjson': '?',
                                            'plot': 'tCV',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_cp_discharge_{:03d}_{}.nox'.format(substrate, int(i+1), 3),
                                            'parseinstructions': 'recordsignal'},
                    f'measure_{14*(i+1)+12}': {'procedure': 'ocp_rs', 
                                            'setpointjson': json.dumps({'recordsignal': {'Duration': 180, 'Interval time in µs': 1}}),
                                            'plot': "tCV",
                                            'onoffafter': "off",
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_ocp_{}_{}.nox'.format(substrate, int(i+1), 3),
                                            'parseinstructions':'recordsignal'},
                    f'measure_{14*(i+1)+13}': {'procedure': 'eis',
                                            'setpointjson': json.dumps({'FHSetSetpointPotential': {'Setpoint value': None}}),
                                            'plot': 'impedance',
                                            'onoffafter': 'off',
                                            'safepath': "C:/Users/LaborRatte23-2/Documents/GitHub/helao-dev_2/temp",
                                            'filename': 'substrate_{}_eis_ocp_{:03d}_{}.nox'.format(substrate, int(i+1), 3),
                                            'parseinstructions': ['FIAMeasPotentiostatic'],
                                            'substrate': substrate,
                                            'id': int(i+1),
                                            'experiment': 3},
                    f'pumpL_{10*(i+1)+7}': {'volume': -75, 'times': 1},
                    f'moveRel_{2*(i+1)}':{'dx': 0, 'dy':0, 'dz':-0.5},
                    f'pumpL_{10*(i+1)+8}': {'volume': -50, 'times': 1},
                    f'moveRel_{2*(i+1)+1}':{'dx': 0, 'dy':0, 'dz':-0.5},
                    f'pumpL_{10*(i+1)+9}': {'volume': -50, 'times': 1},
                    f'moveWaste_{6*(i+1)+5}':{'x': 0, 'y':0, 'z': 0},
                    f'cp_{i+1}':{'query': query, 'address':json.dumps([f'experiment_{i+1}:0/moveSample_{i+1}/parameters/x',
                                                                            f'experiment_{i+1}:0/moveSample_{i+1}/parameters/y',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+2}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+2}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+2}/data/data/recordsignal/WE(1).Potential',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+3}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+3}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+3}/data/data/recordsignal/WE(1).Potential',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+6}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+6}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+6}/data/data/recordsignal/WE(1).Potential',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+7}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+7}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+7}/data/data/recordsignal/WE(1).Potential',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+10}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+10}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+10}/data/data/recordsignal/WE(1).Potential',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+11}/data/data/recordsignal/Corrected time',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+11}/data/data/recordsignal/WE(1).Current',
                                                                            f'experiment_{i+1}:0/measure_{14*(i+1)+11}/data/data/recordsignal/WE(1).Potential'])},
                    f'ocp_{i+1}': {'address':json.dumps([f'experiment_{i+1}:0/measure_{14*(i+1)}/data/data/recordsignal/WE(1).Potential',
                                                        f'experiment_{i+1}:0/measure_{14*(i+1)+4}/data/data/recordsignal/WE(1).Potential',
                                                        f'experiment_{i+1}:0/measure_{14*(i+1)+8}/data/data/recordsignal/WE(1).Potential',
                                                        f'experiment_{i+1}:0/measure_{14*(i+1)+12}/data/data/recordsignal/WE(1).Potential'])},
                    f'eis0_{(i+1)}': {'address':json.dumps([f"experiment_{i+1}:0/measure_{14*(i+1)+1}/data/data/FIAMeasPotentiostatic/Z'",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+1}/data/data/FIAMeasPotentiostatic/-Z''",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+1}/data/data/FIAMeasPotentiostatic/Frequency"])},  
                    f'eis1_{3*(i+1)}': {'address':json.dumps([f"experiment_{i+1}:0/measure_{14*(i+1)+5}/data/data/FIAMeasPotentiostatic/Z'",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+5}/data/data/FIAMeasPotentiostatic/-Z''",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+5}/data/data/FIAMeasPotentiostatic/Frequency"])},
                    f'eis1_{3*(i+1)+1}': {'address':json.dumps([f"experiment_{i+1}:0/measure_{14*(i+1)+9}/data/data/FIAMeasPotentiostatic/Z'",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+9}/data/data/FIAMeasPotentiostatic/-Z''",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+9}/data/data/FIAMeasPotentiostatic/Frequency"])},
                    f'eis1_{3*(i+1)+2}': {'address':json.dumps([f"experiment_{i+1}:0/measure_{14*(i+1)+13}/data/data/FIAMeasPotentiostatic/Z'",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+13}/data/data/FIAMeasPotentiostatic/-Z''",
                                                                f"experiment_{i+1}:0/measure_{14*(i+1)+13}/data/data/FIAMeasPotentiostatic/Frequency"])},                                                                                        
                    f'activeLearningGaussian_{i+1}': {'name': 'sdc_4', 'num': int(i+1), 'query': query, 'address':f'experiment_{i+1}:0/cp_{i+1}/data'}}, 
                  meta=dict()))

test_fnc(dict(soe=['orchestrator/finish'], params={'finish': None}, meta={}))